---
title: "class activity 3"
author: "Charles Lang"
date: "10/2/2018"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

#Mapping aesthetic to data to = layer
```{r}
library(ggplot2)

ggplot(diamonds, aes(x = price, y = carat)) +
  geom_point()
```

#Two layers
```{r}
library(ggplot2)
ggplot(mpg, aes(reorder(class, hwy), hwy)) +
  geom_jitter() +
  geom_boxplot()
```

```{r}

#Plot count
ggplot(diamonds, aes(depth)) +
  geom_histogram(aes(y = ..count..), binwidth=0.2) +
  facet_wrap(~ cut) + xlim(50, 70)

#Plot density
ggplot(diamonds, aes(depth)) +
  geom_histogram(aes(y = ..density..), binwidth=0.2) +
  facet_wrap(~ cut) + xlim(50, 70)
```

```{r}
ggplot(mpg, aes(displ, hwy, color = class)) +
  geom_point()

```

Can you create a line graph using the "economics_long" data set that shows change over time in "value01" for different categories of "variable"?

```{r}
#Line graph with economics_long
  #x = date variable
  #y = value to be graphed
  #group = variable label since data is in long form
ggplot(economics_long, aes(x=date, y=value01, color=variable, group=variable)) + geom_line()
```

If you would like to recreate the Minard graphic of Napoleon's Troops the code is below and the data is in this repo.

```{r}
read.csv("cities.txt")
read.csv("temps.txt")
read.csv("troops.txt")
ggplot(cities, aes(long, lat)) +
  geom_path(aes(size = survivors, colour =
direction,
    group = interaction(group, direction)), data =
troops) +
  geom_text(aes(label = city), hjust = 0, vjust = 1,
size = 4)
# Polish appearance
last_plot() +
  scale_x_continuous("", limits = c(24, 39)) +
  scale_y_continuous("") +
  scale_colour_manual(values = c("grey50","red")) 
```

